### ISSUE TITLE
Documentation nitpick

### ISSUE THREAD

**Issue by smondet** [mirage/ocaml-hex#33]
https://github.com/mirage/ocaml-hex/blob/master/lib/hex.mli#L39

```ocaml
val of_string: ?ignore:char list -> string -> t
(** [of_string s] is the hexadecimal representation of the binary
    string [s]. If [ignore] is set, skip the characters in the list
    when converting. Eg [of_string ~ignore:[' '] "a f"]. The default
    value of [ignore] is [[]]). *)
```

The example uses only characters that are also hexadecimal digits :)

To the casual `melin-document` reader, it looks like `of_string ~ignore:[' '] " a  f "` is going to be `` Hex "AF"``  (instead of `` `Hex "6166"``).

**Comment by 3noch** [comment]
Perhaps, also document how one would parse a string as hex here too, since it's a sensible place to look and where I looked when I was trying to parse hex-as-string into bytes.

**Comment by avsm** [comment]
Great points both! PRs welcome on this (and any other unclear bits as you used it)
