### ISSUE TITLE
Add to/from Cstruct

### ISSUE THREAD

**Issue by trevorsummerssmith** [mirage/ocaml-hex#5]
See conversation: https://github.com/mirleft/ocaml-nocrypto/issues/50

Are you all open to this being added? I was thinking something like:

val of_cstruct : Cstruct.t -> t
val to_cstruct : t -> Cstruct.t

I also like @pqwy comments about ignore chars, so the above could instead be:

val of_cstruct : ?ignore:char list -> Cstruct.t -> t

Am happy to submit a PR. Thanks.

**Comment by samoht** [comment]
a patch for this is indeed very welcome. I think the behaviour of `of_cstruct` and `of_string` should be similar so if you add an optional argument for one you need to do it for the other: in both case, I think adding an `ignore` argument makes sense.

**Comment by trevorsummerssmith** [comment]
@samoht I'm a little conflicted on the interface here. In the current interface, I think it's a little weird to have the ?pretty argument to of_string. It _adds_ whitespace to the `Hex type. I think it makes more sense to have the output functions add to the output, and the input functions ignore, so the interfaces would be:

val of_X : ?ignore -> X -> t
val to_X : ?pretty -> t -> X

Aside: Ideally I'd want ?pretty to be slightly more generic/useful than the current boolean, but I cannot come up with a satisfactory callback signature so I'd be a fan of keeping the current pretty semantics.

Thoughts on this? Obviously this would be interfacing breaking.

**Comment by samoht** [comment]
The pretty argument is useful is you want to pretty-print the generated hexa. That could go a separate function tough (eg. pp_hex). Feel free to break compatibility.
